language: python
python:
  - "2.7"
sudo: true
install: 
  - sh setup/travis-build-core.sh
  - pip install -r requirements.txt
  - "cp data/memory.db.default data/memory.db"
script: 
  - "python tests/check_profile.py"
